# Generated by Django 3.2.13 on 2022-06-08 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('address_company', models.CharField(max_length=200)),
                ('staff_limit_num', models.IntegerField()),
                ('staff_current_num', models.IntegerField(default=0)),
                ('del_flg', models.BooleanField(default=False)),
                ('exclusive_fg', models.BooleanField(default=False)),
                ('created_company_cd', models.IntegerField()),
                ('updated_company_cd', models.IntegerField()),
                ('created_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company',
                'ordering': ['created_at'],
            },
        ),
    ]
