# Generated by Django 3.2.13 on 2023-07-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_usage_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='unlimited_usage',
            field=models.BooleanField(default=False),
        ),
    ]
