# Generated by Django 3.2.13 on 2023-07-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20230709_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='free_usage_count',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
