# Generated by Django 3.2.13 on 2022-11-29 15:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('ward', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'address',
                'ordering': ['created_at'],
            },
        ),
    ]
