# Generated by Django 3.2.13 on 2022-07-28 16:53

from django.db import migrations, models
import upload.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('folder', models.CharField(max_length=50, null=True)),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to=upload.models.upload_to)),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
