# Generated by Django 3.2.13 on 2022-12-22 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_title', models.CharField(max_length=200)),
                ('meeting_time_start', models.DateTimeField()),
                ('meeting_time_end', models.DateTimeField()),
                ('meeting_content', models.CharField(max_length=200)),
                ('calendar_id', models.CharField(max_length=200)),
                ('calendar_url', models.CharField(max_length=200)),
                ('meeting_url', models.CharField(max_length=200)),
                ('conclusion', models.CharField(max_length=200, null=True)),
                ('url_file', models.CharField(default='', max_length=200)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('meeting_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingGuest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_guest', to='meeting.meeting')),
                ('meeting_guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_guest', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_guest',
                'ordering': ['created_at'],
            },
        ),
    ]
