# Generated by Django 3.2.13 on 2023-07-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20230722_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingguest',
            old_name='conclusion',
            new_name='conclusion_guest',
        ),
    ]
