# Generated by Django 3.2.13 on 2023-07-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_rename_conclusion_meetingguest_conclusion_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingguest',
            name='conclusion_guest',
        ),
    ]
