# Generated by Django 3.2.13 on 2023-07-29 17:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0002_auto_20230730_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.BooleanField()),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='patient.patient')),
            ],
            options={
                'db_table': 'pc',
                'ordering': ['created_at'],
            },
        ),
    ]
